module.exports = {
	GameServerError: 0,
	QuickJoinFailed: 1,
	AlreadyPlaying: 2,
	NonExistingChannel: 3,
	ChannelLimitExceed: 4,
	ChannelEnter: 5,
	RoomAllowedPlayerNumberExceed: 6,
	RoomChangeingRules: 7,
	ChannelLeave: 8,
	PlayerCannotBeFound: 9,
	FailedCreatePlayer: 10,
	FailedDeletePlayer: 11,
	FailedSelectPlayer: 12,
	NickCreateSuccess: 13,
	NicknameAlreadyUsed: 14,
	NicknameAvailable: 15,
	PasswordError: 16,
	LoginSuccess: 17,
	LogSpecifiedIP: 18,
	LogForbidden: 19,
	UserAlreadyExist: 20,
	DBError: 21,
	FailedCreatePlayer2: 22,
	CannotEnterChannel: 23,
	RequiredChannelLicense: 24,
	WearingUnusableItem: 25,
	FailResellItemWearing: 26,
	FailEnterRoom: 28,
	ImpossibleToEnterRoom: 29, //FailEnterRoom2: 29,
	TaskCompensationError: 31,
	FailedToRequestTask: 32, //TaskRequestFailed: 32,
	ItemExchangeFailed: 33,
	ItemExchangeFailed2: 34,
	SelectPlayMode: 35,
	SelectGameMode: 35,
	DBError2: 36,
	InventoryFilledWithItems: 37,
	LoginFromElsewhere: 38,
	InventorySuccess: 39
}