module.exports = {
	CKeepAliveAck: 1,
	CLoginReq: 3,
	CChannelLeaveReq: 4,
	CChannelEnterReq: 5,
	CMessageReq: 10,
	CChannelListReq: 12,
	CWhisperReq: 16,
	CAddFriendReq: 26,
	CBRSFriendNotifyReq: 28,
	CDeleteFriendReq: 30,
	CFriendListReq: 36,
	CFriendUnkReq: 46,
	CSetDataReq: 48,
	CGetDataReq: 49,
	CSetStateReq: 51,
	CInviteReq: 54,
	CCombiListReq: 58,
	CAddCombiReq: 60,
	CBRSCombiNotifyReq: 62,
	CDeleteCombiReq: 64,
	CCombiNameReq: 67,
	CAddDenyReq: 83,
	CRemoveDenyReq: 85,
	CDenyListReq: 87,

	SLoginAck: 2,
	SChannelEnterAck: 6,
	SChannelPlayerJoinedAck: 7,
	SChannelPlayerLeftAck: 8,
	SChannelPlayerListInfoAck: 9,
	SMessageAck: 11,
	SChannelListAck: 13,
	SWhisperAck: 17,
	SAddFriendAck: 27,
	SDeleteFriendAck: 31,
	SFriendListAck: 37,
	SGetDataAck: 50,
	SInviteAck: 55,
	SBRSFriendNotifyAck: 57,
	SCombiListAck: 59,
	SAddCombiAck: 61,
	SBRSCombiNotifyAck: 63, // Combi Accept result for the receiver | 0 -> failed
	SDeleteCombiAck: 65,
	SCombiNameAck: 68,
	//Unk: 74, // Unk -> Client Crash
	//Unk: 77, // Unk -> Client Crash
	SAddDenyAck: 84,
	SRemoveDenyAck: 86,
	SDenyListAck: 88//,
	//Unk: 89, // Unk -> Client Crash
}